//!!!!!!!!!!!!!!!!!!! DO NOT CHECK ANY FILE UNDER z-fallout13 DIRECTORY EXCEPT THIS FILE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!//
//Now UTF-8                                                                    //
/////////////////////////////////////////////////////////////////////////////////
//Fallout13 will be split into separate modules.                               //
//At the moment there are only Fallout13 module, which adds some Fallout stuff.//
//Search "//DODELAT" to find some non working shit                             //
/////////////////////////////////////////////////////////////////////////////////

#include "game\GAME.dm"
#include "modules\MODULES.dm"

//F13 DEFINES//

//F13 S.P.E.C.I.A.L and F13 SKILLS and F13 LEVEL SYSTEM and F13 KARMA//
#include "code\z-fallout13\game\objects\items\skill_books.dm"
#include "code\z-fallout13\modules\advanced\skills.dm"
#include "code\z-fallout13\modules\advanced\special.dm"
#include "code\z-fallout13\modules\advanced\experience.dm"
#include "code\z-fallout13\modules\advanced\karma\karma.dm"
#include "code\z-fallout13\modules\advanced\perks\controller.dm"
#include "code\z-fallout13\modules\advanced\perks\hidden.dm"
#include "code\z-fallout13\modules\advanced\perks\perk.dm"

//F13 ENCLAVE SECTION//
#include "code\z-fallout13\modules\advanced\eye\console.dm"
#include "code\z-fallout13\modules\advanced\eye\defines.dm"
#include "code\z-fallout13\modules\advanced\eye\virtual.dm"
#include "code\z-fallout13\modules\advanced\vertibird\defines.dm"
#include "code\z-fallout13\modules\advanced\vertibird\console.dm"
#include "code\z-fallout13\modules\advanced\vertibird\button.dm"
#include "code\z-fallout13\modules\advanced\vertibird\flare.dm"
#include "code\z-fallout13\modules\advanced\vertibird\hatch.dm"
#include "code\z-fallout13\modules\advanced\vertibird\key.dm"
#include "code\z-fallout13\modules\advanced\vertibird\landmark.dm"
#include "code\z-fallout13\modules\advanced\vertibird\vertibird.dm"

#include "code\z-fallout13\modules\machinery\enclave_camera.dm"

//F13 TRADING SYSTEM//
#include "code\z-fallout13\modules\advanced\give.dm"
#include "code\z-fallout13\modules\advanced\trading.dm"
#include "code\z-fallout13\modules\advanced\magazine\defines.dm"
#include "code\z-fallout13\modules\advanced\magazine\magazines.dm"
#include "code\z-fallout13\modules\misc\economy\caps.dm"
#include "code\z-fallout13\modules\advanced\safe\defines.dm"
#include "code\z-fallout13\modules\advanced\safe\safe.dm"


//F13 MODIFICATION//
#include "code\z-fallout13\modules\advanced\defines.dm"
#include "code\z-fallout13\modules\advanced\kit.dm"
#include "code\z-fallout13\modules\advanced\random.dm"
#include "code\z-fallout13\modules\advanced\weapons.dm"

//F13 MAPPING//
#include "code\z-fallout13\modules\advanced\flag.dm"
#include "code\z-fallout13\modules\areas\area.dm"
#include "code\z-fallout13\modules\machinery\chalkboard.dm"
#include "code\z-fallout13\modules\machinery\vending.dm"
#include "code\z-fallout13\modules\machinery\light_sources\bar.dm"
#include "code\z-fallout13\modules\machinery\light_sources\street_light.dm"
#include "code\z-fallout13\game\objects\structures\obstacle.dm"
#include "code\z-fallout13\modules\obj\campfire.dm"
#include "code\z-fallout13\modules\obj\chems.dm"
#include "code\z-fallout13\modules\obj\crafting.dm"
#include "code\z-fallout13\modules\obj\decals.dm"
#include "code\z-fallout13\modules\obj\decor.dm"
#include "code\z-fallout13\modules\obj\door_keys.dm"
#include "code\z-fallout13\modules\obj\explosives.dm"
#include "code\z-fallout13\modules\obj\ground_pit.dm"
#include "code\z-fallout13\modules\obj\holodisks.dm"
#include "code\z-fallout13\modules\obj\items.dm"
#include "code\z-fallout13\modules\obj\krotchy.dm"
#include "code\z-fallout13\modules\obj\train.dm"
#include "code\z-fallout13\modules\obj\trash.dm"
#include "code\z-fallout13\modules\obj\weapons.dm"
#include "code\z-fallout13\modules\obj\flora\farming.dm"
#include "code\z-fallout13\modules\obj\flora\flora.dm"
#include "code\z-fallout13\modules\obj\flora\wildplant.dm"
#include "code\z-fallout13\modules\obj\food_and_drinks\drink.dm"
#include "code\z-fallout13\modules\obj\food_and_drinks\food.dm"
#include "code\z-fallout13\modules\obj\spawners\lootdrops.dm"
#include "code\z-fallout13\modules\obj\spawners\mob_spawner.dm"
#include "code\z-fallout13\modules\obj\stack\grass.dm"
#include "code\z-fallout13\modules\obj\stack\hide.dm"
#include "code\z-fallout13\modules\obj\stack\wood.dm"
#include "code\z-fallout13\modules\obj\structures\barrel.dm"
#include "code\z-fallout13\modules\obj\structures\billboard.dm"
#include "code\z-fallout13\modules\obj\structures\bus_shiny.dm"
#include "code\z-fallout13\modules\obj\structures\chair.dm"
#include "code\z-fallout13\modules\obj\structures\decorations.dm"
#include "code\z-fallout13\modules\obj\structures\fence.dm"
#include "code\z-fallout13\modules\obj\structures\flags.dm"
#include "code\z-fallout13\modules\obj\structures\fridge.dm"
#include "code\z-fallout13\modules\obj\structures\kebabtown.dm"
#include "code\z-fallout13\modules\obj\structures\pole.dm"
#include "code\z-fallout13\modules\obj\structures\radiotower.dm"
#include "code\z-fallout13\modules\obj\structures\randomgarbage.dm"
#include "code\z-fallout13\modules\obj\structures\simple_door.dm"
#include "code\z-fallout13\modules\obj\structures\table_frames.dm"
#include "code\z-fallout13\modules\obj\structures\table_smooth.dm"
#include "code\z-fallout13\modules\obj\structures\tables_racks.dm"
#include "code\z-fallout13\modules\obj\structures\tires.dm"
#include "code\z-fallout13\modules\obj\structures\tubes.dm"
#include "code\z-fallout13\modules\obj\structures\vault_door.dm"
#include "code\z-fallout13\modules\obj\structures\well.dm"
#include "code\z-fallout13\modules\obj\structures\window.dm"
#include "code\z-fallout13\modules\turf\caves.dm"
#include "code\z-fallout13\modules\turf\floor.dm"
#include "code\z-fallout13\modules\turf\ground.dm"
#include "code\z-fallout13\modules\turf\mineral_walls.dm"
#include "code\z-fallout13\modules\turf\plating.dm"
#include "code\z-fallout13\modules\turf\smooth_adjacencies.dm"
#include "code\z-fallout13\modules\turf\wall_damage.dm"
#include "code\z-fallout13\modules\turf\walls.dm"
#include "code\z-fallout13\modules\vehicles\buggy.dm"
#include "code\z-fallout13\modules\vehicles\bus.dm"
#include "code\z-fallout13\modules\vehicles\car.dm"
#include "code\z-fallout13\modules\vehicles\cargocrate.dm"
#include "code\z-fallout13\modules\vehicles\motorcycle.dm"
#include "code\z-fallout13\modules\vehicles\rubish.dm"
#include "code\z-fallout13\modules\vehicles\vehicle_fuel.dm"

//F13 MISC, air system etc.//
#include "code\z-fallout13\modules\advanced\mob_loot.dm"
#include "code\z-fallout13\modules\advanced\hrange.dm"
#include "code\z-fallout13\modules\advanced\teleport.dm"
#include "code\z-fallout13\modules\mob\crawling.dm"
#include "code\z-fallout13\modules\mob\step_sounds.dm"
#include "code\z-fallout13\modules\mob\vision_cone.dm"
#include "code\z-fallout13\modules\misc\air_clearing.dm"
#include "code\z-fallout13\modules\misc\boarding.dm"
#include "code\z-fallout13\modules\misc\curl.dm"
#include "code\z-fallout13\modules\misc\death_screens.dm"
#include "code\z-fallout13\modules\misc\overlays.dm"
#include "code\z-fallout13\modules\misc\radiation.dm"
#include "code\z-fallout13\modules\misc\respawn_mob.dm"
#include "code\z-fallout13\modules\misc\scope_screens.dm"
#include "code\z-fallout13\modules\misc\time_defines_new.dm"
#include "code\z-fallout13\modules\misc\weight.dm"
#include "code\z-fallout13\modules\misc\whitelist.dm"
#include "code\z-fallout13\modules\misc\economy\writing.dm"
#include "code\z-fallout13\modules\misc\objectives\_defines.dm"
#include "code\z-fallout13\modules\misc\objectives\mob.dm"
#include "code\z-fallout13\modules\misc\objectives\objective.dm"
#include "code\z-fallout13\modules\misc\objectives\objective_holder.dm"
#include "code\z-fallout13\modules\misc\objectives\objectives\assasinate.dm"
#include "code\z-fallout13\modules\misc\objectives\objectives\greed.dm"
#include "code\z-fallout13\modules\misc\objectives\objectives\join.dm"
#include "code\z-fallout13\modules\misc\objectives\objectives\protect.dm"
//#include "z-fallout13\modules\misc\objectives\objectives\revolution.dm"
#include "code\z-fallout13\modules\misc\objectives\objectives\faction\expand.dm"
#include "code\z-fallout13\modules\misc\objectives\objectives\faction\find.dm"
#include "code\z-fallout13\modules\misc\sound_system\sound_system.dm"
#include "code\z-fallout13\modules\misc\subsystems\ambient.dm"
#include "code\z-fallout13\modules\misc\subsystems\donate.dm"
#include "code\z-fallout13\modules\misc\subsystems\mob_spawner.dm"
#include "code\z-fallout13\modules\misc\subsystems\objectives.dm"
#include "code\z-fallout13\modules\misc\subsystems\planter.dm"
#include "code\z-fallout13\modules\misc\subsystems\radiation.dm"
#include "code\z-fallout13\modules\misc\subsystems\sunlight.dm"
#include "code\z-fallout13\modules\misc\subsystems\weather.dm"
#include "code\z-fallout13\modules\misc\sun_lighting\corner.dm"
#include "code\z-fallout13\modules\misc\sun_lighting\overlay.dm"
#include "code\z-fallout13\modules\misc\sun_lighting\plane.dm"
#include "code\z-fallout13\modules\misc\sun_lighting\setup.dm"
#include "code\z-fallout13\modules\misc\sun_lighting\source.dm"
#include "code\z-fallout13\modules\misc\sun_lighting\time_of_day_datums.dm"
#include "code\z-fallout13\modules\misc\sun_lighting\turf.dm"
#include "code\z-fallout13\modules\misc\weather\area.dm"
#include "code\z-fallout13\modules\misc\weather\controller.dm"
#include "code\z-fallout13\modules\misc\weather\fog.dm"
#include "code\z-fallout13\modules\misc\weather\rain.dm"
#include "code\z-fallout13\modules\misc\weather\sandstorm.dm"
#include "code\z-fallout13\modules\misc\weather\turf.dm"
#include "code\z-fallout13\modules\mob\human\hairstyle.dm"
#include "code\z-fallout13\modules\verbs\debug.dm"
#include "code\z-fallout13\modules\verbs\playsound.dm"

//F13 ROLES//
#include "code\z-fallout13\modules\misc\jobs\faction.dm"
#include "code\z-fallout13\modules\misc\jobs\job\brotherhood.dm"
#include "code\z-fallout13\modules\misc\jobs\job\city.dm"
#include "code\z-fallout13\modules\misc\jobs\job\enclave.dm"
#include "code\z-fallout13\modules\misc\jobs\job\foa.dm"
#include "code\z-fallout13\modules\misc\jobs\job\ghouls.dm"
#include "code\z-fallout13\modules\misc\jobs\job\gunrunners.dm"
#include "code\z-fallout13\modules\misc\jobs\job\job.dm"
#include "code\z-fallout13\modules\misc\jobs\job\legion.dm"
#include "code\z-fallout13\modules\misc\jobs\job\ncr.dm"
#include "code\z-fallout13\modules\misc\jobs\job\slaver.dm"
#include "code\z-fallout13\modules\misc\jobs\job\wastelander.dm"
#include "code\z-fallout13\modules\misc\jobs\status\status.dm"
#include "code\z-fallout13\modules\mob\human\species\ghoul.dm"
#include "code\z-fallout13\modules\mob\human\species\supermutant.dm"

//F13 DONATE//
#include "code\z-fallout13\modules\misc\donate\job.dm"
#include "code\z-fallout13\modules\misc\donate\loadout_system.dm"
#include "code\z-fallout13\modules\misc\donate\pack.dm"
#include "code\z-fallout13\modules\misc\donate\packs_show.dm"
#include "code\z-fallout13\modules\misc\donate\preferences.dm"
#include "code\z-fallout13\modules\misc\donate\status.dm"
#include "code\z-fallout13\modules\misc\jobs\jobs.dm"
#include "code\z-fallout13\modules\misc\jobs\whitelist.dm"

//F13 CLOTHING//
#include "code\z-fallout13\modules\obj\clothing\radist.dm"
#include "code\z-fallout13\modules\obj\clothing\glasses\glasses.dm"
#include "code\z-fallout13\modules\obj\clothing\gloves\miscellaneous.dm"
#include "code\z-fallout13\modules\obj\clothing\head\helmet.dm"
#include "code\z-fallout13\modules\obj\clothing\head\misc.dm"
#include "code\z-fallout13\modules\obj\clothing\head\soft_caps.dm"
#include "code\z-fallout13\modules\obj\clothing\masks\miscellaneous.dm"
#include "code\z-fallout13\modules\obj\clothing\shoes\shoes.dm"
#include "code\z-fallout13\modules\obj\clothing\suits\power_armor.dm"
#include "code\z-fallout13\modules\obj\clothing\suits\armor.dm"
#include "code\z-fallout13\modules\obj\clothing\suits\labcoat.dm"
#include "code\z-fallout13\modules\obj\clothing\suits\miscellaneous.dm"
#include "code\z-fallout13\modules\obj\clothing\under\miscellaneous.dm"
#include "code\z-fallout13\modules\obj\clothing\under\pants.dm"

//WEAPON//
#include "code\z-fallout13\modules\projectiles\projectile.dm"
#include "code\z-fallout13\modules\projectiles\ammunition\bullets.dm"
#include "code\z-fallout13\modules\projectiles\ammunition\energy.dm"
#include "code\z-fallout13\modules\projectiles\ammunition\magazines.dm"
#include "code\z-fallout13\modules\projectiles\guns\ballistic.dm"
#include "code\z-fallout13\modules\projectiles\guns\energy.dm"

//NPC//
#include "code\z-fallout13\modules\mob\npc\alien.dm"
#include "code\z-fallout13\modules\mob\npc\arachnide.dm"
#include "code\z-fallout13\modules\mob\npc\brahmin.dm"
#include "code\z-fallout13\modules\mob\npc\cazador.dm"
#include "code\z-fallout13\modules\mob\npc\centaur.dm"
#include "code\z-fallout13\modules\mob\npc\deathclaw.dm"
#include "code\z-fallout13\modules\mob\npc\deathclaw_fun.dm"
#include "code\z-fallout13\modules\mob\npc\eyebot.dm"
#include "code\z-fallout13\modules\mob\npc\gecko.dm"
#include "code\z-fallout13\modules\mob\npc\ghost_people.dm"
#include "code\z-fallout13\modules\mob\npc\ghoul.dm"
#include "code\z-fallout13\modules\mob\npc\liberators.dm"
#include "code\z-fallout13\modules\mob\npc\molerat.dm"
#include "code\z-fallout13\modules\mob\npc\mrhandy.dm"
#include "code\z-fallout13\modules\mob\npc\protectron.dm"
#include "code\z-fallout13\modules\mob\npc\rad_scorpion.dm"
#include "code\z-fallout13\modules\mob\npc\radroach.dm"
#include "code\z-fallout13\modules\mob\npc\radstag.dm"
#include "code\z-fallout13\modules\mob\npc\retro_robobrain.dm"
#include "code\z-fallout13\modules\mob\npc\securitron.dm"
#include "code\z-fallout13\modules\mob\npc\sentrybot.dm"
#include "code\z-fallout13\modules\mob\npc\shepka.dm"
#include "code\z-fallout13\modules\mob\npc\supermutant.dm"
#include "code\z-fallout13\modules\mob\npc\synthinstitute.dm"
#include "code\z-fallout13\modules\mob\npc\wolf.dm"
#include "code\z-fallout13\modules\mob\npc\commanded\_commanded.dm"
#include "code\z-fallout13\modules\mob\npc\commanded\bear.dm"
#include "code\z-fallout13\modules\mob\npc\commanded\bruhmin.dm"
#include "code\z-fallout13\modules\mob\npc\commanded\commanded.dm"
#include "code\z-fallout13\modules\mob\npc\commanded\commands_helper.dm"
#include "code\z-fallout13\modules\mob\npc\commanded\dog.dm"
#include "code\z-fallout13\modules\mob\npc\commanded\faction.dm"
#include "code\z-fallout13\modules\mob\npc\commanded\smeagol.dm"